# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ActionHandler.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from arago.pyactionhandler.protobuf import CommonTypes_pb2 as CommonTypes__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ActionHandler.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x13\x41\x63tionHandler.proto\x1a\x11\x43ommonTypes.proto\"\\\n\rActionRequest\x12\x12\n\ncapability\x18\x01 \x02(\t\x12\x10\n\x08time_out\x18\x02 \x02(\x03\x12%\n\x0bparams_list\x18\n \x03(\x0b\x32\x10.KeyValueMessage\"k\n\x0e\x41\x63tionResponse\x12\x0e\n\x06output\x18\x06 \x01(\t\x12\x12\n\nerror_text\x18\x07 \x01(\t\x12\x11\n\tsystem_rc\x18\x08 \x01(\x05\x12\x11\n\tstatusmsg\x18\x03 \x02(\t\x12\x0f\n\x07success\x18\t \x02(\x08\x32I\n\x15\x41\x63tionHandler_Service\x12\x30\n\rPerformAction\x12\x0e.ActionRequest\x1a\x0f.ActionResponseB\x03\x90\x01\x01')
  ,
  dependencies=[CommonTypes__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ACTIONREQUEST = _descriptor.Descriptor(
  name='ActionRequest',
  full_name='ActionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='capability', full_name='ActionRequest.capability', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time_out', full_name='ActionRequest.time_out', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='params_list', full_name='ActionRequest.params_list', index=2,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=134,
)


_ACTIONRESPONSE = _descriptor.Descriptor(
  name='ActionResponse',
  full_name='ActionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='output', full_name='ActionResponse.output', index=0,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error_text', full_name='ActionResponse.error_text', index=1,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='system_rc', full_name='ActionResponse.system_rc', index=2,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='statusmsg', full_name='ActionResponse.statusmsg', index=3,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='success', full_name='ActionResponse.success', index=4,
      number=9, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=243,
)

_ACTIONREQUEST.fields_by_name['params_list'].message_type = CommonTypes__pb2._KEYVALUEMESSAGE
DESCRIPTOR.message_types_by_name['ActionRequest'] = _ACTIONREQUEST
DESCRIPTOR.message_types_by_name['ActionResponse'] = _ACTIONRESPONSE

ActionRequest = _reflection.GeneratedProtocolMessageType('ActionRequest', (_message.Message,), dict(
  DESCRIPTOR = _ACTIONREQUEST,
  __module__ = 'ActionHandler_pb2'
  # @@protoc_insertion_point(class_scope:ActionRequest)
  ))
_sym_db.RegisterMessage(ActionRequest)

ActionResponse = _reflection.GeneratedProtocolMessageType('ActionResponse', (_message.Message,), dict(
  DESCRIPTOR = _ACTIONRESPONSE,
  __module__ = 'ActionHandler_pb2'
  # @@protoc_insertion_point(class_scope:ActionResponse)
  ))
_sym_db.RegisterMessage(ActionResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\220\001\001'))

_ACTIONHANDLER_SERVICE = _descriptor.ServiceDescriptor(
  name='ActionHandler_Service',
  full_name='ActionHandler_Service',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=245,
  serialized_end=318,
  methods=[
  _descriptor.MethodDescriptor(
    name='PerformAction',
    full_name='ActionHandler_Service.PerformAction',
    index=0,
    containing_service=None,
    input_type=_ACTIONREQUEST,
    output_type=_ACTIONRESPONSE,
    options=None,
  ),
])

ActionHandler_Service = service_reflection.GeneratedServiceType('ActionHandler_Service', (_service.Service,), dict(
  DESCRIPTOR = _ACTIONHANDLER_SERVICE,
  __module__ = 'ActionHandler_pb2'
  ))

ActionHandler_Service_Stub = service_reflection.GeneratedServiceStubType('ActionHandler_Service_Stub', (ActionHandler_Service,), dict(
  DESCRIPTOR = _ACTIONHANDLER_SERVICE,
  __module__ = 'ActionHandler_pb2'
  ))


# @@protoc_insertion_point(module_scope)
