# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CommonTypes.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CommonTypes.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x11\x43ommonTypes.proto\"\x0e\n\x0c\x45mptyMessage\"\x1e\n\rStringMessage\x12\r\n\x05value\x18\x01 \x02(\t\"\x1f\n\x0e\x42ooleanMessage\x12\r\n\x05value\x18\x02 \x02(\x08\"\x1d\n\x0cInt64Message\x12\r\n\x05value\x18\x03 \x02(\x03\"0\n\x0eStringResponse\x12\r\n\x05value\x18\x04 \x02(\t\x12\x0f\n\x07success\x18\x05 \x02(\x08\"3\n\x12StringListResponse\x12\x0c\n\x04list\x18\x06 \x03(\t\x12\x0f\n\x07success\x18\x07 \x02(\x08\")\n\rTwoIDsMessage\x12\x0b\n\x03id1\x18\x01 \x02(\t\x12\x0b\n\x03id2\x18\x02 \x02(\t\"F\n\x13GetAttributeRequest\x12\x0e\n\x06nodeid\x18\x01 \x02(\t\x12\x11\n\tparentuid\x18\x02 \x02(\t\x12\x0c\n\x04\x61ttr\x18\x03 \x02(\t\"U\n\x13SetAttributeRequest\x12\x0e\n\x06nodeid\x18\x01 \x02(\t\x12\x11\n\tparentuid\x18\x02 \x02(\t\x12\x0c\n\x04\x61ttr\x18\x03 \x02(\t\x12\r\n\x05value\x18\x04 \x02(\t\"G\n\x13\x44\x65lAttributeRequest\x12\x0f\n\x07issueid\x18\x01 \x02(\t\x12\x11\n\tparentuid\x18\x02 \x02(\t\x12\x0c\n\x04\x61ttr\x18\x03 \x02(\t\"Y\n\x11\x42\x61seObjectMessage\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\n\n\x02id\x18\x02 \x02(\t\x12\x0c\n\x04type\x18\x03 \x02(\t\x12\r\n\x05\x63time\x18\x04 \x02(\x03\x12\r\n\x05mtime\x18\x05 \x02(\x03\"-\n\x0fKeyValueMessage\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\"\x9b\x01\n\x0f\x42\x61seDataMessage\x12 \n\x04\x62\x61se\x18\x01 \x02(\x0b\x32\x12.BaseObjectMessage\x12\x0e\n\x06nodeid\x18\x02 \x02(\t\x12\x11\n\tparentuid\x18\x03 \x01(\t\x12$\n\nattributes\x18\t \x03(\x0b\x32\x10.KeyValueMessage\x12\x1d\n\x03sub\x18\n \x03(\x0b\x32\x10.BaseDataMessage\"H\n\x15StringOrErrorResponse\x12\r\n\x05value\x18\x03 \x02(\t\x12\x0f\n\x07message\x18\x04 \x02(\t\x12\x0f\n\x07success\x18\x05 \x02(\x08\x42(\n&de.arago.autopilot.client.zmq.protobuf')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_EMPTYMESSAGE = _descriptor.Descriptor(
  name='EmptyMessage',
  full_name='EmptyMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=35,
)


_STRINGMESSAGE = _descriptor.Descriptor(
  name='StringMessage',
  full_name='StringMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='StringMessage.value', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=67,
)


_BOOLEANMESSAGE = _descriptor.Descriptor(
  name='BooleanMessage',
  full_name='BooleanMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='BooleanMessage.value', index=0,
      number=2, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=100,
)


_INT64MESSAGE = _descriptor.Descriptor(
  name='Int64Message',
  full_name='Int64Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='Int64Message.value', index=0,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=131,
)


_STRINGRESPONSE = _descriptor.Descriptor(
  name='StringResponse',
  full_name='StringResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='StringResponse.value', index=0,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='success', full_name='StringResponse.success', index=1,
      number=5, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=181,
)


_STRINGLISTRESPONSE = _descriptor.Descriptor(
  name='StringListResponse',
  full_name='StringListResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='list', full_name='StringListResponse.list', index=0,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='success', full_name='StringListResponse.success', index=1,
      number=7, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=234,
)


_TWOIDSMESSAGE = _descriptor.Descriptor(
  name='TwoIDsMessage',
  full_name='TwoIDsMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id1', full_name='TwoIDsMessage.id1', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id2', full_name='TwoIDsMessage.id2', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=277,
)


_GETATTRIBUTEREQUEST = _descriptor.Descriptor(
  name='GetAttributeRequest',
  full_name='GetAttributeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodeid', full_name='GetAttributeRequest.nodeid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parentuid', full_name='GetAttributeRequest.parentuid', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attr', full_name='GetAttributeRequest.attr', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=349,
)


_SETATTRIBUTEREQUEST = _descriptor.Descriptor(
  name='SetAttributeRequest',
  full_name='SetAttributeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodeid', full_name='SetAttributeRequest.nodeid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parentuid', full_name='SetAttributeRequest.parentuid', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attr', full_name='SetAttributeRequest.attr', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='SetAttributeRequest.value', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=351,
  serialized_end=436,
)


_DELATTRIBUTEREQUEST = _descriptor.Descriptor(
  name='DelAttributeRequest',
  full_name='DelAttributeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='issueid', full_name='DelAttributeRequest.issueid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parentuid', full_name='DelAttributeRequest.parentuid', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attr', full_name='DelAttributeRequest.attr', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=438,
  serialized_end=509,
)


_BASEOBJECTMESSAGE = _descriptor.Descriptor(
  name='BaseObjectMessage',
  full_name='BaseObjectMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='BaseObjectMessage.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='id', full_name='BaseObjectMessage.id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='BaseObjectMessage.type', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ctime', full_name='BaseObjectMessage.ctime', index=3,
      number=4, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mtime', full_name='BaseObjectMessage.mtime', index=4,
      number=5, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=511,
  serialized_end=600,
)


_KEYVALUEMESSAGE = _descriptor.Descriptor(
  name='KeyValueMessage',
  full_name='KeyValueMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='KeyValueMessage.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='KeyValueMessage.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=602,
  serialized_end=647,
)


_BASEDATAMESSAGE = _descriptor.Descriptor(
  name='BaseDataMessage',
  full_name='BaseDataMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='base', full_name='BaseDataMessage.base', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nodeid', full_name='BaseDataMessage.nodeid', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parentuid', full_name='BaseDataMessage.parentuid', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attributes', full_name='BaseDataMessage.attributes', index=3,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sub', full_name='BaseDataMessage.sub', index=4,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=650,
  serialized_end=805,
)


_STRINGORERRORRESPONSE = _descriptor.Descriptor(
  name='StringOrErrorResponse',
  full_name='StringOrErrorResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='StringOrErrorResponse.value', index=0,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='StringOrErrorResponse.message', index=1,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='success', full_name='StringOrErrorResponse.success', index=2,
      number=5, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=807,
  serialized_end=879,
)

_BASEDATAMESSAGE.fields_by_name['base'].message_type = _BASEOBJECTMESSAGE
_BASEDATAMESSAGE.fields_by_name['attributes'].message_type = _KEYVALUEMESSAGE
_BASEDATAMESSAGE.fields_by_name['sub'].message_type = _BASEDATAMESSAGE
DESCRIPTOR.message_types_by_name['EmptyMessage'] = _EMPTYMESSAGE
DESCRIPTOR.message_types_by_name['StringMessage'] = _STRINGMESSAGE
DESCRIPTOR.message_types_by_name['BooleanMessage'] = _BOOLEANMESSAGE
DESCRIPTOR.message_types_by_name['Int64Message'] = _INT64MESSAGE
DESCRIPTOR.message_types_by_name['StringResponse'] = _STRINGRESPONSE
DESCRIPTOR.message_types_by_name['StringListResponse'] = _STRINGLISTRESPONSE
DESCRIPTOR.message_types_by_name['TwoIDsMessage'] = _TWOIDSMESSAGE
DESCRIPTOR.message_types_by_name['GetAttributeRequest'] = _GETATTRIBUTEREQUEST
DESCRIPTOR.message_types_by_name['SetAttributeRequest'] = _SETATTRIBUTEREQUEST
DESCRIPTOR.message_types_by_name['DelAttributeRequest'] = _DELATTRIBUTEREQUEST
DESCRIPTOR.message_types_by_name['BaseObjectMessage'] = _BASEOBJECTMESSAGE
DESCRIPTOR.message_types_by_name['KeyValueMessage'] = _KEYVALUEMESSAGE
DESCRIPTOR.message_types_by_name['BaseDataMessage'] = _BASEDATAMESSAGE
DESCRIPTOR.message_types_by_name['StringOrErrorResponse'] = _STRINGORERRORRESPONSE

EmptyMessage = _reflection.GeneratedProtocolMessageType('EmptyMessage', (_message.Message,), dict(
  DESCRIPTOR = _EMPTYMESSAGE,
  __module__ = 'CommonTypes_pb2'
  # @@protoc_insertion_point(class_scope:EmptyMessage)
  ))
_sym_db.RegisterMessage(EmptyMessage)

StringMessage = _reflection.GeneratedProtocolMessageType('StringMessage', (_message.Message,), dict(
  DESCRIPTOR = _STRINGMESSAGE,
  __module__ = 'CommonTypes_pb2'
  # @@protoc_insertion_point(class_scope:StringMessage)
  ))
_sym_db.RegisterMessage(StringMessage)

BooleanMessage = _reflection.GeneratedProtocolMessageType('BooleanMessage', (_message.Message,), dict(
  DESCRIPTOR = _BOOLEANMESSAGE,
  __module__ = 'CommonTypes_pb2'
  # @@protoc_insertion_point(class_scope:BooleanMessage)
  ))
_sym_db.RegisterMessage(BooleanMessage)

Int64Message = _reflection.GeneratedProtocolMessageType('Int64Message', (_message.Message,), dict(
  DESCRIPTOR = _INT64MESSAGE,
  __module__ = 'CommonTypes_pb2'
  # @@protoc_insertion_point(class_scope:Int64Message)
  ))
_sym_db.RegisterMessage(Int64Message)

StringResponse = _reflection.GeneratedProtocolMessageType('StringResponse', (_message.Message,), dict(
  DESCRIPTOR = _STRINGRESPONSE,
  __module__ = 'CommonTypes_pb2'
  # @@protoc_insertion_point(class_scope:StringResponse)
  ))
_sym_db.RegisterMessage(StringResponse)

StringListResponse = _reflection.GeneratedProtocolMessageType('StringListResponse', (_message.Message,), dict(
  DESCRIPTOR = _STRINGLISTRESPONSE,
  __module__ = 'CommonTypes_pb2'
  # @@protoc_insertion_point(class_scope:StringListResponse)
  ))
_sym_db.RegisterMessage(StringListResponse)

TwoIDsMessage = _reflection.GeneratedProtocolMessageType('TwoIDsMessage', (_message.Message,), dict(
  DESCRIPTOR = _TWOIDSMESSAGE,
  __module__ = 'CommonTypes_pb2'
  # @@protoc_insertion_point(class_scope:TwoIDsMessage)
  ))
_sym_db.RegisterMessage(TwoIDsMessage)

GetAttributeRequest = _reflection.GeneratedProtocolMessageType('GetAttributeRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETATTRIBUTEREQUEST,
  __module__ = 'CommonTypes_pb2'
  # @@protoc_insertion_point(class_scope:GetAttributeRequest)
  ))
_sym_db.RegisterMessage(GetAttributeRequest)

SetAttributeRequest = _reflection.GeneratedProtocolMessageType('SetAttributeRequest', (_message.Message,), dict(
  DESCRIPTOR = _SETATTRIBUTEREQUEST,
  __module__ = 'CommonTypes_pb2'
  # @@protoc_insertion_point(class_scope:SetAttributeRequest)
  ))
_sym_db.RegisterMessage(SetAttributeRequest)

DelAttributeRequest = _reflection.GeneratedProtocolMessageType('DelAttributeRequest', (_message.Message,), dict(
  DESCRIPTOR = _DELATTRIBUTEREQUEST,
  __module__ = 'CommonTypes_pb2'
  # @@protoc_insertion_point(class_scope:DelAttributeRequest)
  ))
_sym_db.RegisterMessage(DelAttributeRequest)

BaseObjectMessage = _reflection.GeneratedProtocolMessageType('BaseObjectMessage', (_message.Message,), dict(
  DESCRIPTOR = _BASEOBJECTMESSAGE,
  __module__ = 'CommonTypes_pb2'
  # @@protoc_insertion_point(class_scope:BaseObjectMessage)
  ))
_sym_db.RegisterMessage(BaseObjectMessage)

KeyValueMessage = _reflection.GeneratedProtocolMessageType('KeyValueMessage', (_message.Message,), dict(
  DESCRIPTOR = _KEYVALUEMESSAGE,
  __module__ = 'CommonTypes_pb2'
  # @@protoc_insertion_point(class_scope:KeyValueMessage)
  ))
_sym_db.RegisterMessage(KeyValueMessage)

BaseDataMessage = _reflection.GeneratedProtocolMessageType('BaseDataMessage', (_message.Message,), dict(
  DESCRIPTOR = _BASEDATAMESSAGE,
  __module__ = 'CommonTypes_pb2'
  # @@protoc_insertion_point(class_scope:BaseDataMessage)
  ))
_sym_db.RegisterMessage(BaseDataMessage)

StringOrErrorResponse = _reflection.GeneratedProtocolMessageType('StringOrErrorResponse', (_message.Message,), dict(
  DESCRIPTOR = _STRINGORERRORRESPONSE,
  __module__ = 'CommonTypes_pb2'
  # @@protoc_insertion_point(class_scope:StringOrErrorResponse)
  ))
_sym_db.RegisterMessage(StringOrErrorResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n&de.arago.autopilot.client.zmq.protobuf'))
# @@protoc_insertion_point(module_scope)
