# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: IssueAPI.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import arago.pyactionhandler.protobuf.CommonTypes_pb2 as CommonTypes__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='IssueAPI.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0eIssueAPI.proto\x1a\x11\x43ommonTypes.proto\"\xa0\x01\n\x18IssueHistoryEntryMessage\x12\x11\n\ttimestamp\x18\x01 \x02(\x03\x12\r\n\x05ki_id\x18\x02 \x02(\t\x12\x0f\n\x07node_id\x18\x03 \x02(\t\x12\x14\n\x0c\x65lement_name\x18\x04 \x02(\t\x12\x17\n\x0f\x65lement_message\x18\x05 \x02(\t\x12\x11\n\tlog_level\x18\x06 \x02(\x05\x12\x0f\n\x07issueid\x18\x07 \x02(\t\"\x87\x01\n\x16IssueDescriptorMessage\x12\x14\n\x0cmodel_nodeid\x18\x01 \x02(\t\x12\r\n\x05state\x18\x02 \x02(\t\x12\x14\n\x0clast_message\x18\x03 \x02(\t\x12\x10\n\x08\x63ustomer\x18\x04 \x02(\t\x12 \n\x04\x62\x61se\x18\x05 \x02(\x0b\x32\x12.BaseObjectMessage\",\n\x10IssueTextMessage\x12\n\n\x02id\x18\x01 \x02(\t\x12\x0c\n\x04text\x18\x02 \x02(\t2\xa4\x03\n\x10IssueAPI_Service\x12\'\n\x04List\x12\x0e.StringMessage\x1a\x0f.BooleanMessage\x12.\n\x04Read\x12\x0e.StringMessage\x1a\x16.StringOrErrorResponse\x12/\n\x05Write\x12\x0e.StringMessage\x1a\x16.StringOrErrorResponse\x12*\n\x07Resolve\x12\x0e.StringMessage\x1a\x0f.StringResponse\x12\x35\n\x0cGetAttribute\x12\x14.GetAttributeRequest\x1a\x0f.StringResponse\x12\x35\n\x0cSetAttribute\x12\x14.SetAttributeRequest\x1a\x0f.BooleanMessage\x12=\n\x0f\x41\x64\x64HistoryEntry\x12\x19.IssueHistoryEntryMessage\x1a\x0f.BooleanMessage\x12-\n\nGetHistory\x12\x0e.StringMessage\x1a\x0f.StringResponse2V\n\x15IssueListener_Service\x12=\n\x11HistoryEntryAdded\x12\x19.IssueHistoryEntryMessage\x1a\r.EmptyMessageB1\n&de.arago.autopilot.client.zmq.protobuf\x80\x01\x01\x88\x01\x01\x90\x01\x01')
  ,
  dependencies=[CommonTypes__pb2.DESCRIPTOR,])




_ISSUEHISTORYENTRYMESSAGE = _descriptor.Descriptor(
  name='IssueHistoryEntryMessage',
  full_name='IssueHistoryEntryMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='IssueHistoryEntryMessage.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ki_id', full_name='IssueHistoryEntryMessage.ki_id', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='node_id', full_name='IssueHistoryEntryMessage.node_id', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='element_name', full_name='IssueHistoryEntryMessage.element_name', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='element_message', full_name='IssueHistoryEntryMessage.element_message', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='log_level', full_name='IssueHistoryEntryMessage.log_level', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='issueid', full_name='IssueHistoryEntryMessage.issueid', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=198,
)


_ISSUEDESCRIPTORMESSAGE = _descriptor.Descriptor(
  name='IssueDescriptorMessage',
  full_name='IssueDescriptorMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_nodeid', full_name='IssueDescriptorMessage.model_nodeid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state', full_name='IssueDescriptorMessage.state', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_message', full_name='IssueDescriptorMessage.last_message', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='customer', full_name='IssueDescriptorMessage.customer', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='base', full_name='IssueDescriptorMessage.base', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=336,
)


_ISSUETEXTMESSAGE = _descriptor.Descriptor(
  name='IssueTextMessage',
  full_name='IssueTextMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='IssueTextMessage.id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='text', full_name='IssueTextMessage.text', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=338,
  serialized_end=382,
)

_ISSUEDESCRIPTORMESSAGE.fields_by_name['base'].message_type = CommonTypes__pb2._BASEOBJECTMESSAGE
DESCRIPTOR.message_types_by_name['IssueHistoryEntryMessage'] = _ISSUEHISTORYENTRYMESSAGE
DESCRIPTOR.message_types_by_name['IssueDescriptorMessage'] = _ISSUEDESCRIPTORMESSAGE
DESCRIPTOR.message_types_by_name['IssueTextMessage'] = _ISSUETEXTMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IssueHistoryEntryMessage = _reflection.GeneratedProtocolMessageType('IssueHistoryEntryMessage', (_message.Message,), dict(
  DESCRIPTOR = _ISSUEHISTORYENTRYMESSAGE,
  __module__ = 'IssueAPI_pb2'
  # @@protoc_insertion_point(class_scope:IssueHistoryEntryMessage)
  ))
_sym_db.RegisterMessage(IssueHistoryEntryMessage)

IssueDescriptorMessage = _reflection.GeneratedProtocolMessageType('IssueDescriptorMessage', (_message.Message,), dict(
  DESCRIPTOR = _ISSUEDESCRIPTORMESSAGE,
  __module__ = 'IssueAPI_pb2'
  # @@protoc_insertion_point(class_scope:IssueDescriptorMessage)
  ))
_sym_db.RegisterMessage(IssueDescriptorMessage)

IssueTextMessage = _reflection.GeneratedProtocolMessageType('IssueTextMessage', (_message.Message,), dict(
  DESCRIPTOR = _ISSUETEXTMESSAGE,
  __module__ = 'IssueAPI_pb2'
  # @@protoc_insertion_point(class_scope:IssueTextMessage)
  ))
_sym_db.RegisterMessage(IssueTextMessage)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n&de.arago.autopilot.client.zmq.protobuf\200\001\001\210\001\001\220\001\001'))

_ISSUEAPI_SERVICE = _descriptor.ServiceDescriptor(
  name='IssueAPI_Service',
  full_name='IssueAPI_Service',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=385,
  serialized_end=805,
  methods=[
  _descriptor.MethodDescriptor(
    name='List',
    full_name='IssueAPI_Service.List',
    index=0,
    containing_service=None,
    input_type=CommonTypes__pb2._STRINGMESSAGE,
    output_type=CommonTypes__pb2._BOOLEANMESSAGE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Read',
    full_name='IssueAPI_Service.Read',
    index=1,
    containing_service=None,
    input_type=CommonTypes__pb2._STRINGMESSAGE,
    output_type=CommonTypes__pb2._STRINGORERRORRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Write',
    full_name='IssueAPI_Service.Write',
    index=2,
    containing_service=None,
    input_type=CommonTypes__pb2._STRINGMESSAGE,
    output_type=CommonTypes__pb2._STRINGORERRORRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Resolve',
    full_name='IssueAPI_Service.Resolve',
    index=3,
    containing_service=None,
    input_type=CommonTypes__pb2._STRINGMESSAGE,
    output_type=CommonTypes__pb2._STRINGRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetAttribute',
    full_name='IssueAPI_Service.GetAttribute',
    index=4,
    containing_service=None,
    input_type=CommonTypes__pb2._GETATTRIBUTEREQUEST,
    output_type=CommonTypes__pb2._STRINGRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetAttribute',
    full_name='IssueAPI_Service.SetAttribute',
    index=5,
    containing_service=None,
    input_type=CommonTypes__pb2._SETATTRIBUTEREQUEST,
    output_type=CommonTypes__pb2._BOOLEANMESSAGE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AddHistoryEntry',
    full_name='IssueAPI_Service.AddHistoryEntry',
    index=6,
    containing_service=None,
    input_type=_ISSUEHISTORYENTRYMESSAGE,
    output_type=CommonTypes__pb2._BOOLEANMESSAGE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetHistory',
    full_name='IssueAPI_Service.GetHistory',
    index=7,
    containing_service=None,
    input_type=CommonTypes__pb2._STRINGMESSAGE,
    output_type=CommonTypes__pb2._STRINGRESPONSE,
    options=None,
  ),
])

IssueAPI_Service = service_reflection.GeneratedServiceType('IssueAPI_Service', (_service.Service,), dict(
  DESCRIPTOR = _ISSUEAPI_SERVICE,
  __module__ = 'IssueAPI_pb2'
  ))

IssueAPI_Service_Stub = service_reflection.GeneratedServiceStubType('IssueAPI_Service_Stub', (IssueAPI_Service,), dict(
  DESCRIPTOR = _ISSUEAPI_SERVICE,
  __module__ = 'IssueAPI_pb2'
  ))



_ISSUELISTENER_SERVICE = _descriptor.ServiceDescriptor(
  name='IssueListener_Service',
  full_name='IssueListener_Service',
  file=DESCRIPTOR,
  index=1,
  options=None,
  serialized_start=807,
  serialized_end=893,
  methods=[
  _descriptor.MethodDescriptor(
    name='HistoryEntryAdded',
    full_name='IssueListener_Service.HistoryEntryAdded',
    index=0,
    containing_service=None,
    input_type=_ISSUEHISTORYENTRYMESSAGE,
    output_type=CommonTypes__pb2._EMPTYMESSAGE,
    options=None,
  ),
])

IssueListener_Service = service_reflection.GeneratedServiceType('IssueListener_Service', (_service.Service,), dict(
  DESCRIPTOR = _ISSUELISTENER_SERVICE,
  __module__ = 'IssueAPI_pb2'
  ))

IssueListener_Service_Stub = service_reflection.GeneratedServiceStubType('IssueListener_Service_Stub', (IssueListener_Service,), dict(
  DESCRIPTOR = _ISSUELISTENER_SERVICE,
  __module__ = 'IssueAPI_pb2'
  ))


# @@protoc_insertion_point(module_scope)
